In [47]:
import numpy as np
import pandas as pd
# Series是pandas的一种数据结构，在pandas中，默认以float64来存储数据
s = pd.Series([1, 3, 6, np.nan, 44, 1])  
print(s)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [48]:
# date_range 日期表序列,第一个参数表示起始日期，第二个参数表示序列个数
# dtpye是日期
dates = pd.date_range("20180201", periods=6)
print(dates)


DatetimeIndex(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
               '2018-02-05', '2018-02-06'],
              dtype='datetime64[ns]', freq='D')


In [86]:
# DataFrame是pandas的另一种数据结构,相当于一张表，当不指定行和列的表头时，默认从0开始标号，示例如下。
data1 = pd.DataFrame(np.arange(12).reshape(3, 4))
print(data1)

# 若指定表头，则需要带上index参数和columns参数
data2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['a', 'b', 'c', 'd'])
data2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


a         b         c         d
2018-02-01 -0.627418 -0.623238 -0.957666 -0.992986
2018-02-02  0.292329  0.473569  0.939141  0.227174
2018-02-03  2.104086  0.540964 -0.011172 -0.675875
2018-02-04 -1.154923  0.602626 -1.360081  0.538327
2018-02-05  1.705209  0.121180  0.605148  0.203812
2018-02-06 -0.707460 -1.400066  0.777646 -0.289695

In [50]:
# 还可以使用字典来代替上述的columns,但必须至少有一个字典的value值是列表，否则会出错
data3 = pd.DataFrame({'x':[1,2,3,4,5],'y':['a','a','b','b','c']})
print(data3)
print('--------------------')
data3 = pd.DataFrame({'x':[2, 3],'y': 2})
print(data3)

   x  y
0  1  a
1  2  a
2  3  b
3  4  b
4  5  c
--------------------
   x  y
0  2  2
1  3  2


In [51]:
# dtypes属性，使用该属性可以看Seris或DataFrame元素的数据类型
print(s.dtypes)
print('----------------------')
print(data3.dtypes)

float64
----------------------
x    int64
y    int64
dtype: object


In [52]:
# index属性，使用 该属性可以输出所有行的名字
print(s.index)
print(data2.index)
print(data3.index)

RangeIndex(start=0, stop=6, step=1)
DatetimeIndex(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
               '2018-02-05', '2018-02-06'],
              dtype='datetime64[ns]', freq='D')
RangeIndex(start=0, stop=2, step=1)


In [53]:
# columns属性，使用该属性可以打印DataFrame所有列的名字
print(data2.columns)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [54]:
# values属性，使用该属性可以打印Sereis和DataFrame的值
print(s.values)
print(data2.values)

[ 1.  3.  6. nan 44.  1.]
[[-0.36653126  0.9671432   2.92517818 -1.10615897]
 [-0.50175694 -1.3390985  -0.01997823  1.25239191]
 [ 0.14936062  1.34879475  0.99723994 -0.03291228]
 [-1.10481198 -0.28603855 -0.91955535 -0.11218188]
 [-2.44361966  0.2523115   0.84739061  1.24223709]
 [ 0.71404173  1.12805734 -1.62449118  0.10262123]]


In [55]:
# describe方法，显示整个DataFrame的简介，它只能运算数字，对于非数值型数据，describe会产生另外一种汇总统计。


# count表示每一类的元素，mean表示算术平均值，std表示标准差，min表示最小值，max表示最大值，25%：25%分位数，50% 50%分位数(中位数)，75%：75%分位数
print(data2.describe())

              a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean  -0.592220  0.345195  0.367631  0.224333
std    1.095976  1.024776  1.608929  0.900830
min   -2.443620 -1.339098 -1.624491 -1.106159
25%   -0.954048 -0.151451 -0.694661 -0.092364
50%   -0.434144  0.609727  0.413706  0.034854
75%    0.020388  1.087829  0.959778  0.957333
max    0.714042  1.348795  2.925178  1.252392


In [56]:
# sort_index方法，针对对应维度进行排序，参数axis表示维度，可选参数ascending：True表示升序，False表示降序
data2.sort_index(axis=0)

a         b         c         d
2018-02-01 -0.366531  0.967143  2.925178 -1.106159
2018-02-02 -0.501757 -1.339098 -0.019978  1.252392
2018-02-03  0.149361  1.348795  0.997240 -0.032912
2018-02-04 -1.104812 -0.286039 -0.919555 -0.112182
2018-02-05 -2.443620  0.252311  0.847391  1.242237
2018-02-06  0.714042  1.128057 -1.624491  0.102621

In [57]:
# sort_value方法，针对值进行排序，参数by表示针对第几列,可选参数ascending：True表示升序，False表示降序
print(data2.sort_values(by='a', ascending=False))

                   a         b         c         d
2018-02-06  0.714042  1.128057 -1.624491  0.102621
2018-02-03  0.149361  1.348795  0.997240 -0.032912
2018-02-01 -0.366531  0.967143  2.925178 -1.106159
2018-02-02 -0.501757 -1.339098 -0.019978  1.252392
2018-02-04 -1.104812 -0.286039 -0.919555 -0.112182
2018-02-05 -2.443620  0.252311  0.847391  1.242237


In [58]:
# DataFrame的索引
print(data2['a'])
print(data2.a) # 这种写法和上述写法等价,取列索引为'a'的一列]
print('-----------------------')
print(data2[0:3]) # 选择data2的第0行到第2行
print(data2['20180201': '20180203']) # 这种写法与上述写法等价

2018-02-01   -0.366531
2018-02-02   -0.501757
2018-02-03    0.149361
2018-02-04   -1.104812
2018-02-05   -2.443620
2018-02-06    0.714042
Freq: D, Name: a, dtype: float64
2018-02-01   -0.366531
2018-02-02   -0.501757
2018-02-03    0.149361
2018-02-04   -1.104812
2018-02-05   -2.443620
2018-02-06    0.714042
Freq: D, Name: a, dtype: float64
-----------------------
                   a         b         c         d
2018-02-01 -0.366531  0.967143  2.925178 -1.106159
2018-02-02 -0.501757 -1.339098 -0.019978  1.252392
2018-02-03  0.149361  1.348795  0.997240 -0.032912
                   a         b         c         d
2018-02-01 -0.366531  0.967143  2.925178 -1.106159
2018-02-02 -0.501757 -1.339098 -0.019978  1.252392
2018-02-03  0.149361  1.348795  0.997240 -0.032912


In [59]:
# DeataFrame selcet by label, 选择带有指定行标签或列标签的一整行或多行

#loc方法是local的缩写，用来对标签进行选择
print(data2.loc['20180203'])  # 选择带有20180203的一整行
print(data2.loc[:, ['a', 'b']]) # 选择带有a标签和b标签的2列
print('-------------------------------')
print(data2.loc['20180203',['a', 'b']]) # 选择同时带有行标签和列标签的那一个值


a    0.149361
b    1.348795
c    0.997240
d   -0.032912
Name: 2018-02-03 00:00:00, dtype: float64
                   a         b
2018-02-01 -0.366531  0.967143
2018-02-02 -0.501757 -1.339098
2018-02-03  0.149361  1.348795
2018-02-04 -1.104812 -0.286039
2018-02-05 -2.443620  0.252311
2018-02-06  0.714042  1.128057
-------------------------------
a    0.149361
b    1.348795
Name: 2018-02-03 00:00:00, dtype: float64


In [60]:
# iloc方法，与loc方法的区别是iloc是根据行号和列号来确定索引的
print(data2.iloc[3]) # 选择第3行整行的数据
print('---------------------')
print(data2.iloc[2, 2]) # 选择第二行第二列的数据
print('---------------------')
print(data2.iloc[3:5, 1:3]) # 选择第三行到第四行的和第1列第2列的数据
print('---------------------')
print(data2.iloc[[1, 3, 5], 1:3]) # 选择不连续的三行以及第1列和第2列的数据

a   -1.104812
b   -0.286039
c   -0.919555
d   -0.112182
Name: 2018-02-04 00:00:00, dtype: float64
---------------------
0.9972399352053056
---------------------
                   b         c
2018-02-04 -0.286039 -0.919555
2018-02-05  0.252311  0.847391
---------------------
                   b         c
2018-02-02 -1.339098 -0.019978
2018-02-04 -0.286039 -0.919555
2018-02-06  1.128057 -1.624491


In [61]:
# ix方法，实现表现和行列号的混合筛选, pandas不推荐使用，已经被弃用
print(data2.ix[1:3, ['a', 'c']])

                   a         c
2018-02-02 -0.501757 -0.019978
2018-02-03  0.149361  0.997240


D:\ProgramFiles\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [62]:
# 比较运算符筛选
print(data2< 0)
print('------------------')
print(data2[data2.a < 1])  # 如果某一列名字为T，则无法使用点运算符调用，而且会直接转置

                a      b      c      d
2018-02-01   True  False  False   True
2018-02-02   True   True   True  False
2018-02-03  False  False  False   True
2018-02-04   True   True   True   True
2018-02-05   True  False  False  False
2018-02-06  False  False   True  False
------------------
                   a         b         c         d
2018-02-01 -0.366531  0.967143  2.925178 -1.106159
2018-02-02 -0.501757 -1.339098 -0.019978  1.252392
2018-02-03  0.149361  1.348795  0.997240 -0.032912
2018-02-04 -1.104812 -0.286039 -0.919555 -0.112182
2018-02-05 -2.443620  0.252311  0.847391  1.242237
2018-02-06  0.714042  1.128057 -1.624491  0.102621
