In [3]:
import numpy as np

# 定义一个二维的2行3列数组
array = np.array([[1, 2, 3],
                  [4,5, 6]])
print(array)
print("number of dimension:", array.ndim)
print("shape:", array.shape)
print("size:", array.size)

[[1 2 3]
 [4 5 6]]
number of dimension: 2
shape: (2, 3)
size: 6


In [4]:
# array的元素属性称为dtype，可以自定义，默认为列表中最高级的类型。
# 默认是int32，和float64，如果需要32位，可以写成np.int32和np.float64
A = np.array([1, 2333383, 4, 55], dtype=np.int)
print(A.dtype)

int32


In [14]:
# 定义一个3行2列的矩阵全零矩阵
zero = np.zeros((3, 2))
print(zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
# 定义一个3行2列的空矩阵，实际上不是空矩阵，是一个无意义的值
empty = np.empty((3, 2))
print(empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# 定义一个一维等差数组，起始是10，末尾是20，步长是2,传入的值是不包括末尾
arange = np.arange(10,19, 3)
print(arange)

[10 13 16]


In [27]:
# 改变数组的shape,如果元素不足则会报错
arange1 = arange.reshape(2, 2)
print(arange1)

[[10 13]
 [16 19]]


In [30]:
# 定义一个5行4列等差数组(使用linspace创建的一维等差数组又称线段），起始是10，结尾是20，一共有20个元素
linspace = np.linspace(10, 20, 20).reshape(5, 4)
print(linspace)

[[10.         10.52631579 11.05263158 11.57894737]
 [12.10526316 12.63157895 13.15789474 13.68421053]
 [14.21052632 14.73684211 15.26315789 15.78947368]
 [16.31578947 16.84210526 17.36842105 17.89473684]
 [18.42105263 18.94736842 19.47368421 20.        ]]


In [34]:
# numpy的一维数组四则运算
a = np.array([100, 200, 300, 400])
b = np.arange(1, 5)
print(a + b) # 加法
print(a - b) # 减法
print(a * b) # 乘法
print(a / b) # 除法
print(b ** 2) #平方

[101 202 303 404]
[ 99 198 297 396]
[ 100  400  900 1600]
[100. 100. 100. 100.]
[ 1  4  9 16]


In [36]:
# 判断矩阵与某个值的关系
print(a)
print(a > 200)

[100 200 300 400]
[False False  True  True]


In [38]:
# numpy二(n)维数组(矩阵)的四则运算
a = np.array([[0, 1],
              [1, 0]])
b = np.arange(1, 5).reshape(2, 2)
print(a * b)  # 普通乘号为逐个相乘
print(a.dot(b)) # dot方法为矩阵乘法
print(np.dot(a, b)) #跟上述的dot方法等价


[[0 2]
 [3 0]]
[[3 4]
 [1 2]]
[[3 4]
 [1 2]]


In [40]:
# 创建一个随机生成的array,下述是一个2行4列的数组
a = np.random.random((2, 4))
print(a)

[[3.47415973e-01 7.23522808e-04 8.39990182e-01 7.02378378e-01]
 [4.07840570e-02 5.52537457e-01 4.41854631e-01 5.19415534e-01]]


In [44]:
# 计算矩阵中的最大值，最小值，求和
# 通过指定不同的axis，numpy会沿着不同的方向进行操作，如果不设置，则表示对所有的元素进行操作，
# 如果axis=0，则沿着纵轴进行操作，若axis=1则沿着横轴进行操作。但是这只是仅仅对于二维数组而言。
# 但是可以总结为一句话：设axis=i ,则numpy沿着第i个下标变化的方向进行操作
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.max(a, axis=1)) # axis代表维度，0代表行，1代表列，依次类推 ，如果axis=1表示行的最大值，axis=0表示列的最大值

0.8399901822412776
0.0007235228076358791
3.445099735031879
[0.83999018 0.55253746]


In [45]:
# 计算矩阵最大值，最小值的索引
print(np.argmax(a))
print(np.argmin(a))

2
1


In [64]:
# 计算矩阵的平均值和中位数，可指定axis参数
print(a)
print(np.mean(a))
print(a.mean())   # 与上面的写法等价
print(np.average(a)) # 与上面的写法等价，但是average函数可以计算加权平均数，而mean直接计算平均数
print(np.median(a))
print(np.median(a, axis=1)) # axis=1返回每一行的平均值数组，axis=0返回每一列的平均值数组
#这里可以想象成数组的合并，axis=1表示把所有元组合并到第一列，所以相当于求行平均，axis=0表示把所有元素合并到第一行，所以相当于求列平均

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
8.5
8.5
8.5
8.5
[12.5  8.5  4.5]


In [7]:
# 生成一个累加和累的数组
a = np.arange(1, 17).reshape((4, 4))
print(np.cumsum(a)) # 第一个元素是第一个的值，第二个的元素第一个和第二个元素的值，依此类推
print(a)
# diff函数如果对二位数组使用，则对每一个数组单独求一次diff，如下面的例子，每一行后一个元素减前一个元素的差都是1，所以得到12个1的矩阵
print(np.diff(a))  # 第一个元素是第一个的值，第二个是它和前一个元素的差，第三个是第三个元素和第二个元素的差，依次类推

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [52]:
# 找出数组中的非零数,返回2个array，第一个表示行索引，第二个表示列索引，比如第一个表示0行0列的数是非0元素
print(np.nonzero(a))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [57]:
# 对数组元素逐行进行排序
a = np.arange(14, 2, -1).reshape((3, 4))
print(a)
print(np.sort(a))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [60]:
# 矩阵的转置
print(a)
print(np.transpose(a))
print(a.T) # 与上述写法等价

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [61]:
# 限制矩阵元素的值在最小值(3)和最大值(9)之间，所以大于9的数都变成9，所以小于3的元素都变成3
print(np.clip(a, 3, 9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 4 3]]


In [5]:
# 数组的索引
a = np.arange(1, 13).reshape(3, 4)
print(a)
print(a[2])
print(a[2][3])
print(a[2, 3]) # 与上述写法等价
print(a[2,:]) # 第2行所有数
print(a[:,1]) # 第1列所有数

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
12
12
[ 9 10 11 12]
[ 2  6 10]


In [6]:
# 迭代数组的每一行，每一列
for row in a:
    print(row)

for col in a.T:  # 迭代矩阵的转置从而迭代行
    print(col)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [8]:
# 把n维数组变成一维数组
for e in a.flat:  # a.flat是一个迭代器
    print(e)
print(a.flatten()) # a.flateen()返回一个一维数组

1
2
3
4
5
6
7
8
9
10
11
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
# 合并array
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])
print(np.vstack((a, b))) # vertical stack 上下合并(1,3) + (1,3) = (2, 3)
print(np.hstack((a, b))) # herizontal stack 左右合并 （1,3） + （1，3） = （1，6）

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [18]:
# 实现序列(一维数组)真正的转置

print(a.shape)
print(a.T.shape)
# 观察到，上述的转置根本没有改变原序列的shape,因为一维数组只有行而没有列

#给数组增加一个在行(列)上增加一个维度
print(a[np.newaxis,:])
print(a[:, np.newaxis])

#我们可以使用给列增加维度来实现一维数组的转置
a = np.array([1, 1, 1])[:, np.newaxis]
b = np.array([2, 2, 2])[:, np.newaxis]
print(a.T.shape)  # 这样就实现了一维数组的转置


(3, 1)
(1, 3)
[[[1]
  [1]
  [1]]]
[[[1]]

 [[1]]

 [[1]]]
(1, 3)


In [19]:
#还可以对一位数组的shape属性进行操作
a = np.array([1, 1, 1])
print(a.shape)
a.shape = (3, 1)
print(a.shape)
print(a.T.shape)

(3,)
(3, 1)
(1, 3)


In [20]:
# 或者使用reshape函数对其进行操作
a = np.array([1, 1, 1])
a = a.reshape(a.shape[0], 1)
print(a.shape)
print(a.T.shape)

(3, 1)
(1, 3)


In [24]:
# 数组的分割 注，split函数无法进行不等的分割
a = np.arange(12).reshape(3, 4)
print(a)
print(np.split(a, 2, axis=1)) # 沿着纵轴分割
print(np.split(a, 3, axis=0)) # 沿着横轴分割 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [25]:
# 数组的分割 array_split函数可以进行不等的分割
print(np.array_split(a, 3, axis=1))  #分割的三个array中，第一个包含了2列，后面的只包含1列

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [26]:
# 更简便的分割函数
print(np.vsplit(a, 3))  # 纵向分割成3块
print(np.hsplit(a, 2))  # 横向分割成2份

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [33]:
# 数组的浅拷贝和深拷贝
a = np.arange(4)
print(a)
b = a
a[0] = 4
print(b)  # 此处是浅拷贝，只是b指向a数组的索引，a改变了b也会被改变
print(b is a)  # is是身份运算符，判断两个标识符是不是引用自一个对象
c = a.copy()   # copy函数是一个深拷贝函数，会重新分配一个内存给新数组，不会与a进行关联
a[1] = 3
print(c)  # 此处a改变c不会被改变


[0 1 2 3]
[4 1 2 3]
True
[4 1 2 3]
